name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: bcmath

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          configuration: phpunit.xml.dist
          php_extensions: bcmath
          args: tests --coverage-clover ./coverage.xml

          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODE_COV_TOKEN }}
            files: ./coverage.xml
            verbose: true